#!/bin/bash
##************************************************************************
## slua/tools/testsh
##
## Copyright (c) 2013 Michael D Henderson
##
## Permission is hereby granted, free of charge, to any person obtaining a
## copy of this software and associated documentation files (the "Software"),
## to deal in the Software without restriction, including without limitation
## the rights to use, copy, modify, merge, publish, distribute, sublicense,
## and/or sell copies of the Software, and to permit persons to whom the
## Software is furnished to do so, subject to the following conditions:
##
## The above copyright notice and this permission notice shall be included
## in all copies or substantial portions of the Software.
##
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
## OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
## THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
## LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
## FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
## DEALINGS IN THE SOFTWARE.
##
##************************************************************************

tc=PASS
tx=
while [ -n "${1}" ]
do
  case "${1}" in
    pass) tc="PASS" ;;
    warn) tc="WARN" ;;
    fail) tc="FAIL" ;;
       *) tx="${1}"; shift; break ;;
  esac
  shift
done
if [ -z "${tx}" ]
then
  echo "error: you must give a command to execute"
  exit 2
elif [ ! -f "${tx}" ]
then
  echo "error: unable to find command '${tx}'"
  exit 2
elif [ ! -x "${tx}" ]
then
  echo "error: unable to execute command '${tx}'"
  exit 2
fi

"${tx}" $*

case "$?" in
  0) rc=PASS ;;
  1) rc=WARN ;;
  *) rc=FAIL ;;
esac

echo " info: expected ${tc}, got ${rc}"

if [ "${tc}" == "${rc}" ]
then
  exit 0
fi
exit 2
